/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/editor/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["TestController_list"];
    put: operations["TestController_create"];
    post: operations["TestController_update"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/editor/test/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["TestController_single"];
    put?: never;
    post?: never;
    delete: operations["TestController_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    TestModel: {
      id: string;
      name: number;
      email: string;
      /** Format: date-time */
      deletedTime: string;
    };
    CreateTestDto: {
      name: number;
      email: string;
    };
    UpdateTestDto: {
      id: string;
      name: number;
      email: string;
    };
    ExceptionResponseDto: {
      source: string;
      statusCode: number;
      message: string;
      path: string;
      timestamp: string;
    };
    /** @enum {string} */
    StyleValueKind: "text" | "color" | "number" | "length" | "boolean";
    /** @enum {string} */
    StyleValueUnit: "px" | "rem" | "%";
    /** @enum {string} */
    StyleValueFormat: "hex" | "rgb" | "rgba" | "hsl" | "hsla";
    ComponentStyleModel: {
      id: string;
      componentVariantId: string | null;
      label: string;
      cssProperty: string;
      valueKind: components["schemas"]["StyleValueKind"];
      stringValue: string | null;
      numberValue: number | null;
      booleanValue: boolean | null;
      unit: components["schemas"]["StyleValueUnit"] | null;
      format: components["schemas"]["StyleValueFormat"] | null;
    };
    ComponentPropsModel: {
      style: components["schemas"]["ComponentStyleModel"][];
    };
    ComponentVariantModel: {
      id: string;
      key: string;
      name: string;
      order: string;
      props: components["schemas"]["ComponentPropsModel"];
    };
    ComponentModel: {
      id: string;
      name: string;
      tagName: string;
      props: components["schemas"]["ComponentPropsModel"];
      variants: components["schemas"]["ComponentVariantModel"][];
    };
    ComponentManifestModel: {
      componentVersionId: string;
      componentVersion: string;
      components: components["schemas"]["ComponentModel"][];
    };
    DesignTokenValueModel: {
      id: string;
      name: string;
      stringValue: string | null;
      numberValue: number | null;
      booleanValue: boolean | null;
      unit: components["schemas"]["StyleValueUnit"] | null;
      format: components["schemas"]["StyleValueFormat"] | null;
    };
    DesignTokenModel: {
      id: string;
      name: string;
      valueKind: components["schemas"]["StyleValueKind"];
      values: components["schemas"]["DesignTokenValueModel"][];
    };
    DesignTokenGroupModel: {
      id: string;
      name: string;
      designTokens: components["schemas"]["DesignTokenModel"][];
    };
    PageTreeStyleOverrideModel: {
      id: string;
      componentStyleId: string;
      stringValue: string | null;
      numberValue: number | null;
      booleanValue: boolean | null;
      unit: components["schemas"]["StyleValueUnit"] | null;
      format: components["schemas"]["StyleValueFormat"] | null;
      designTokenValueId: string | null;
    };
    PageTreeModel: {
      id: string;
      stableId: string;
      pageId: string;
      componentId: string;
      componentVariantId: string | null;
      parentId: string | null;
      order: number;
      styleOverrides: components["schemas"]["PageTreeStyleOverrideModel"][];
      children: components["schemas"]["PageTreeModel"][];
    };
    PageModel: {
      id: string;
      stableId: string;
      spaceId: string;
      name: string;
      order: string;
      rootPageTree: components["schemas"]["PageTreeModel"] | null;
    };
    ProjectComponentStylePresetModel: {
      id: string;
      componentVariantId: string | null;
      componentStyleId: string;
      stringValue: string | null;
      numberValue: number | null;
      booleanValue: boolean | null;
      unit: components["schemas"]["StyleValueUnit"] | null;
      format: components["schemas"]["StyleValueFormat"] | null;
      designTokenId: string | null;
      designTokenValueId: string | null;
    };
    ProjectComponentPresetModel: {
      id: string;
      componentId: string;
      stylePresets: components["schemas"]["ProjectComponentStylePresetModel"][];
    };
    ProjectModel: {
      id: string;
      currentRevisionId: string;
      name: string;
      description: string;
      componentPresets: components["schemas"]["ProjectComponentPresetModel"][];
    };
    /** @enum {number} */
    RevisionStatus: 0 | 1;
    RevisionModel: {
      id: string;
      parentRevisionId: string | null;
      componentVersionId: string;
      name: string;
      createdBy: string;
      description: string;
      status: components["schemas"]["RevisionStatus"];
    };
    /** @enum {number} */
    SpacePlacementKind: 0 | 1 | 2 | 3;
    SpacePlacementModel: {
      id: string;
      stableId: string;
      spaceId: string;
      kind: components["schemas"]["SpacePlacementKind"];
      targetId: string;
      pageViewportId: string | null;
      x: number;
      y: number;
      width: number;
      height: number;
      zIndex: number;
      order: number;
    };
    SpaceModel: {
      id: string;
      stableId: string;
      name: string;
      order: number;
      pages: components["schemas"]["PageModel"][];
      placements: components["schemas"]["SpacePlacementModel"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  TestController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestModel"][];
        };
      };
    };
  };
  TestController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTestDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestModel"];
        };
      };
    };
  };
  TestController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTestDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestModel"];
        };
      };
    };
  };
  TestController_single: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestModel"];
        };
      };
    };
  };
  TestController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}

export namespace Models {}
