/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/editor/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["TestController_list"];
    put: operations["TestController_create"];
    post: operations["TestController_update"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/editor/test/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["TestController_single"];
    put?: never;
    post?: never;
    delete: operations["TestController_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    TestModel: {
      id: string;
      name: number;
      email: string;
      /** Format: date-time */
      deletedTime: string;
    };
    CreateTestDto: {
      name: number;
      email: string;
    };
    UpdateTestDto: {
      id: string;
      name: number;
      email: string;
    };
    ExceptionResponseDto: {
      source: string;
      statusCode: number;
      message: string;
      path: string;
      timestamp: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  TestController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Models.TestModel[];
        };
      };
    };
  };
  TestController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": Models.CreateTestDto;
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Models.TestModel;
        };
      };
    };
  };
  TestController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": Models.UpdateTestDto;
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Models.TestModel;
        };
      };
    };
  };
  TestController_single: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Models.TestModel;
        };
      };
    };
  };
  TestController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}

export namespace Models {
  export interface TestModel {
    id: string;
    name: number;
    email: string;
    /** Format: date-time */
    deletedTime: string;
  }

  export interface CreateTestDto {
    name: number;
    email: string;
  }

  export interface UpdateTestDto {
    id: string;
    name: number;
    email: string;
  }

  export interface ExceptionResponseDto {
    source: string;
    statusCode: number;
    message: string;
    path: string;
    timestamp: string;
  }
}
