/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/component-lab/component-manifest/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["ComponentLabComponentManifestController_upload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export type $defs = Record<string, never>;
export interface operations {
  ComponentLabComponentManifestController_upload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          "bundle.zip": string;
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}

export namespace Models {
  export interface ComponentManifestVariantModel {
    key: string;
    order: number;
  }

  export interface ComponentManifestPropModel {
    key: string;
    required: boolean;
    value:
      | Models.ComponentManifestStringPropValueModel
      | Models.ComponentManifestNumberPropValueModel
      | Models.ComponentManifestBooleanPropValueModel
      | Models.ComponentManifestStringEnumPropValueModel
      | Models.ComponentManifestNumberEnumPropValueModel
      | Models.ComponentManifestObjectPropValueModel
      | Models.ComponentManifestArrayPropValueModel
      | Models.ComponentManifestStylePropertiesPropValueModel
      | Models.ComponentManifestUnknownPropValueModel;
  }

  export interface ComponentManifestStyleModel {
    variantKey: string;
    cssProperty: string;
    rawValue: string;
  }

  export interface ComponentManifestPartModel {
    tagName: string;
    kind: Enums.ComponentPartKind;
    order: number;
    styles: Models.ComponentManifestStyleModel[];
    children: Models.ComponentManifestPartModel[];
  }

  export interface ComponentManifestComponentModel {
    name: string;
    placementType: Enums.ComponentPlacementType;
    variants: Models.ComponentManifestVariantModel[];
    props: Models.ComponentManifestPropModel[];
    parts: Models.ComponentManifestPartModel[];
  }

  export interface ComponentManifestStringPropValueModel {
    /**
     * @description discriminator enum property added by openapi-typescript
     * @enum {string}
     */
    type: "String";
    defaultValue?: string;
  }

  export interface ComponentManifestNumberPropValueModel {
    /**
     * @description discriminator enum property added by openapi-typescript
     * @enum {string}
     */
    type: "Number";
    defaultValue?: number;
  }

  export interface ComponentManifestBooleanPropValueModel {
    /**
     * @description discriminator enum property added by openapi-typescript
     * @enum {string}
     */
    type: "Boolean";
    defaultValue?: boolean;
  }

  export interface ComponentManifestStringEnumPropValueModel {
    /**
     * @description discriminator enum property added by openapi-typescript
     * @enum {string}
     */
    type: "StringEnum";
    values: string[];
    defaultValue?: string;
  }

  export interface ComponentManifestNumberEnumPropValueModel {
    /**
     * @description discriminator enum property added by openapi-typescript
     * @enum {string}
     */
    type: "NumberEnum";
    values: number[];
    defaultValue?: number;
  }

  export interface ComponentManifestObjectPropValueModel {
    /**
     * @description discriminator enum property added by openapi-typescript
     * @enum {string}
     */
    type: "Object";
    properties: Models.ComponentManifestPropModel[];
  }

  export interface ComponentManifestStylePropertiesPropValueModel {
    /**
     * @description discriminator enum property added by openapi-typescript
     * @enum {string}
     */
    type: "StyleProperties";
    defaultValue?: Record<string, never>;
  }

  export interface ComponentManifestUnknownPropValueModel {
    /**
     * @description discriminator enum property added by openapi-typescript
     * @enum {string}
     */
    type: "Unknown";
    rawType?: string;
  }

  export interface ComponentManifestArrayPropValueModel {
    /**
     * @description discriminator enum property added by openapi-typescript
     * @enum {string}
     */
    type: "Array";
    item:
      | Models.ComponentManifestStringPropValueModel
      | Models.ComponentManifestNumberPropValueModel
      | Models.ComponentManifestBooleanPropValueModel
      | Models.ComponentManifestStringEnumPropValueModel
      | Models.ComponentManifestNumberEnumPropValueModel
      | Models.ComponentManifestObjectPropValueModel
      | Models.ComponentManifestArrayPropValueModel
      | Models.ComponentManifestStylePropertiesPropValueModel
      | Models.ComponentManifestUnknownPropValueModel;
    defaultValue?: Record<string, never>[];
  }

  export interface ComponentManifestUploadModel {
    generatedAt: string[];
    files: string[];
    components: Models.ComponentManifestComponentModel[];
  }
}

export namespace Enums {
  export enum ComponentPlacementType {
    "Standalone" = "Standalone",
    "Fragment" = "Fragment",
  }

  export enum ComponentPartKind {
    "Element" = "Element",
    "Component" = "Component",
  }

  export enum ComponentPropType {
    "String" = "String",
    "Number" = "Number",
    "Boolean" = "Boolean",
    "StringEnum" = "StringEnum",
    "NumberEnum" = "NumberEnum",
    "Object" = "Object",
    "Array" = "Array",
    "StyleProperties" = "StyleProperties",
    "Unknown" = "Unknown",
  }
}
